### ISSUE TITLE
Executing ./gradlew build --scan results in interactive prompt and consecutive timeout of the build

### ISSUE THREAD

**Issue by Stvad** [gradle-guides/executing-gradle-builds-on-travisci#2]
Hey I just followed the guide and I'm facing the following problem - if I'm to run the build with the scan option as suggested - the gradle stops with the interactive prompt to accept scan usage conditions.

Given that there is no way for me to interact with the travis build session - I can't accept those conditions and as a consequence - the build eventually times out. 

I'd appreciate a suggestion on how I can work around this issue (besides not adding `--scan` option).

**Comment by briandealwis** [comment]
@Stvad I think the following section should help: https://docs.gradle.com/build-scan-plugin/#accept_the_scans_gradle_com_terms_of_service

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #218](https://github.com/gradle/guides/issues/218) via [**ZenHub**](https://www.zenhub.com/)
