### ISSUE TITLE
Cache config guidance differs from gradle-site-plugin

### ISSUE THREAD

**Issue by 3flex** [gradle-guides/executing-gradle-builds-on-travisci#9]
https://github.com/gradle-guides/gradle-site-plugin/pull/21 changed the Travis caching config from what's recommended in this guide.

I'd expect the plugin best practice example to match docs, so if the docs need updating to align, would be good to do that to ensure the most efficient config is recommended.

Thanks!

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #296](https://github.com/gradle/guides/issues/296) via [**ZenHub**](https://www.zenhub.com/)
